# Generated by Django 5.2.5 on 2025-08-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0003_message_deleted_message_edited'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='message',
            name='edited',
        ),
    ]
